### ISSUE TITLE
measureEC -1 reading error 

### ISSUE THREAD

**Issue by bogdan42k** [u-fire/Isolated_EC#2]
Hi,
I have the Isolated EC Probe Interface + Waterproof Temperature Sensor + Industrial Conductivity Probe.
I tested the examples from this repo and get -1 error when measuring EC. Temperature reading is fine.
Hardware version is 2 and firmware version is 3. Tested with 3.3V Arduino Pro Mini and Arduino Uno, both 3.3V and 5V and got the same issue. The BNC connector is fully locked.
Am I missing something?

**Comment by justind000** [comment]
What is the expected EC of the water? If it is under 0.5 mS, which may be the case for tap water, it is under the range of the device. [characteristics](https://www.ufire.co/docs/uFire_EC/#characteristics).

Also, for the industrial sensor, be sure there is no air trapped in the bottom portion of the sensor where the hole is. It tends to hold air when first submerged, but once water flows through, it rarely becomes an issue later.

**Comment by bogdan42k** [comment]
I think there was air trapped in the bottom hole and didn't realize. Also the -1 returned value was misleading and I supposed to be some hardware error.
I tested it with different fluids and it works the way it should.
Thanks!
